export const supportedCurrency = [
    { key: 'AFN', value: 'Afghan Afghani' },
    { key: 'DZD', value: 'Algerian Dinar' },
    { key: 'AOA', value: 'Angolan Kwanza' },
    { key: 'AMD', value: 'Armenian Dram' },
    { key: 'AUD', value: 'Australian Dollar' },
    { key: 'BHD', value: 'Bahraini Dinar' },
    { key: 'BDT', value: 'Bangladeshi Taka' },
    { key: 'BBD', value: 'Barbadian or Bajan Dollar' },
    { key: 'LSL', value: 'Basotho Loti' },
    { key: 'BYN', value: 'Belarusian Ruble' },
    { key: 'BMD', value: 'Bermudian Dollar' },
    { key: 'BOB', value: 'Bolivian Bolíviano' },
    { key: 'BAM', value: 'Bosnian Convertible Marka' },
    { key: 'BRL', value: 'Brazilian Real' },
    { key: 'GBP', value: 'British Pound' },
    { key: 'BGN', value: 'Bulgarian Lev' },
    { key: 'MMK', value: 'Burmese Kyat' },
    { key: 'KHR', value: 'Cambodian Riel' },
    { key: 'CAD', value: 'Canadian Dollar' },
    { key: 'KYD', value: 'Caymanian Dollar' },
    { key: 'XAF', value: 'Central African CFA Franc BEAC' },
    { key: 'XOF', value: 'CFA Franc' },
    { key: 'CNY', value: 'Chinese Yuan Renminbi' },
    { key: 'HRK', value: 'Croatian Kuna' },
    { key: 'CUC', value: 'Cuban Convertible Peso' },
    { key: 'CUP', value: 'Cuban Peso' },
    { key: 'DKK', value: 'Danish Krone' },
    { key: 'DOP', value: 'Dominican Peso' },
    { key: 'AED', value: 'Emirati Dirham' },
    { key: 'EUR', value: 'Euro' },
    { key: 'FJD', value: 'Fijian Dollar' },
    { key: 'GEL', value: 'Georgian Lari' },
    { key: 'GHS', value: 'Ghanaian Cedi' },
    { key: 'GIP', value: 'Gibraltar Pound' },
    { key: 'XAU', value: 'Gold Ounce' },
    { key: 'GGP', value: 'Guernsey Pound' },
    { key: 'GYD', value: 'Guyanese Dollar' },
    { key: 'HKD', value: 'Hong Kong Dollar' },
    { key: 'HUF', value: 'Hungarian Forint' },
    { key: 'INR', value: 'Indian Rupee' },
    { key: 'IDR', value: 'Indonesian Rupiah' },
    { key: 'IRR', value: 'Iranian Rial' },
    { key: 'ILS', value: 'Israeli Shekel' },
    { key: 'JMD', value: 'Jamaican Dollar' },
    { key: 'JPY', value: 'Japanese Yen' },
    { key: 'JOD', value: 'Jordanian Dinar' },
    { key: 'KZT', value: 'Kazakhstani Tenge' },
    { key: 'KWD', value: 'Kuwaiti Dinar' },
    { key: 'KGS', value: 'Kyrgyzstani Som' },
    { key: 'LBP', value: 'Lebanese Pound' },
    { key: 'LRD', value: 'Liberian Dollar' },
    { key: 'MOP', value: 'Macau Pataca' },
    { key: 'MGA', value: 'Malagasy Ariary' },
    { key: 'MYR', value: 'Malaysian Ringgit' },
    { key: 'MUR', value: 'Mauritian Rupee' },
    { key: 'MXN', value: 'Mexican Peso' },
    { key: 'MDL', value: 'Moldovan Leu' },
    { key: 'MAD', value: 'Moroccan Dirham' },
    { key: 'MZN', value: 'Mozambican Metical' },
    { key: 'NZD', value: 'New Zealand Dollar' },
    { key: 'NIO', value: 'Nicaraguan Cordoba' },
    { key: 'NGN', value: 'Nigerian Naira' },
    { key: 'KPW', value: 'North Korean Won' },
    { key: 'PKR', value: 'Pakistani Rupee' },
    { key: 'PAB', value: 'Panamanian Balboa' },
    { key: 'PEN', value: 'Peruvian Sol' },
    { key: 'PHP', value: 'Philippine Piso' },
    { key: 'XPT', value: 'Platinum Ounce' },
    { key: 'PLN', value: 'Polish Zloty' },
    { key: 'QAR', value: 'Qatari Riyal' },
    { key: 'RON', value: 'Romanian Leu' },
    { key: 'RUB', value: 'Russian Ruble' },
    { key: 'SAR', value: 'Saudi Arabian Riyal' },
    { key: 'RSD', value: 'Serbian Dinar' },
    { key: 'SCR', value: 'Seychellois Rupee' },
    { key: 'SGD', value: 'Singapore Dollar' },
    { key: 'SBD', value: 'Solomon Islander Dollar' },
    { key: 'ZAR', value: 'South African Rand' },
    { key: 'LKR', value: 'Sri Lankan Rupee' },
    { key: 'SEK', value: 'Swedish Krona' },
    { key: 'CHF', value: 'Swiss Franc' },
    { key: 'THB', value: 'Thai Baht' },
    { key: 'TND', value: 'Tunisian Dinar' },
    { key: 'UGX', value: 'Ugandan Shilling' },
    { key: 'UAH', value: 'Ukrainian Hryvnia' },
    { key: 'UYU', value: 'Uruguayan Peso' },
    { key: 'USD', value: 'US Dollar' },
    { key: 'UZS', value: 'Uzbekistani Som' },
    { key: 'VEF', value: 'Venezuelan Bolívar' },
    { key: 'VND', value: 'Vietnamese Dong' },
    { key: 'YER', value: 'Yemeni Rial' },
    { key: 'ZMW', value: 'Zambian Kwacha' },
    { key: 'ZWD', value: 'Zimbabwean Dollar' }
];
